-- MySQL Script generated by MySQL Workbench
-- Fri Aug 25 16:06:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  `senha_usuario` VARCHAR(45) NULL,
  `foto_usuario` VARCHAR(90) NULL,
  UNIQUE INDEX `nome_usuario_UNIQUE` (`nome_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_usuario_UNIQUE` (`email_usuario` ASC) VISIBLE,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_postagens` (
  `id_postagens` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `conteudo` LONGTEXT NOT NULL,
  `data_da_publicacao` DATE NOT NULL,
  `autor_id` BIGINT NOT NULL,
  PRIMARY KEY (`id_postagens`),
  INDEX `fk_usuario_postagens_idx` (`autor_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_postagens`
    FOREIGN KEY (`autor_id`)
    REFERENCES `mydb`.`tb_usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_comentario` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `comentario` LONGTEXT NOT NULL,
  `data_comentario` DATE NULL,
  `autor_id` BIGINT NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_autor_comentario_idx` (`autor_id` ASC) VISIBLE,
  CONSTRAINT `fk_autor_comentario`
    FOREIGN KEY (`autor_id`)
    REFERENCES `mydb`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
